name: dataframes-package
version: '0.9.0.0'
synopsis: A general utility for building and developing Flowbox
version: "1.1.4"
author: New Byte Order <contact@newbyteorder.com>
maintainer: New Byte Order <contact@newbyteorder.com>

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

executables:
  dataframes-package:
    main: Main.hs
    source-dirs: .
    ghc-options: -threaded -Werror=missing-fields

dependencies:
- base
- Cabal
- containers
- directory
- extra
- filepath
- Glob
- MissingH
- process
- temporary
- text
- typed-process