name: dataframes-package
synopsis: Utility program to build, test and create relocatable package with Dataframes library
version: "1.0"
author: New Byte Order <contact@newbyteorder.com>
maintainer: New Byte Order <contact@newbyteorder.com>

ghc-options: -threaded -Werror=missing-fields

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveGeneric
- DuplicateRecordFields
- FlexibleContexts
- FlexibleInstances
- FunctionalDependencies
- GeneralizedNewtypeDeriving
- LambdaCase
- OverloadedStrings
- RankNTypes
- ScopedTypeVariables
- StandaloneDeriving
- TemplateHaskell
- TupleSections
- TypeApplications
- TypeFamilies
- TypeOperators
- ViewPatterns

library:
  source-dirs: src

executable:
  main: Main.hs
  dependencies: dataframes-package

dependencies:
- base
- bytestring
- Cabal
- containers
- directory
- extra
- file-embed
- filepath
- Glob
- MissingH
- process
- typed-process
- temporary
- text
- unix-compat